name: widget_to_html
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  meta: any

dev_dependencies:
  lints: any
  test: any
  html: any
